name: build and publish container

on: [push]
env:
  ## Sets environment variable
  DOCKER_HUB_ORGANIZATION: tawoe
  DOCKER_HUB_REPOSITORY: obp-api


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - uses: sigstore/cosign-installer@main

      - name: Write signing key to disk (only needed for `cosign sign --key`)
        run: echo "${{ secrets.SIGNING_SECRET }}" > cosign.key

      - name: Sign container image
        run: |
          cat cosign.key
          cosign sign --key cosign.key \
            docker.io/${{ env.DOCKER_HUB_ORGANIZATION }}/${{ env.DOCKER_HUB_REPOSITORY }}:develop
        env:
          COSIGN_PASSWORD: "${{secrets.COSIGN_PASSWORD}}"





