name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: Build with Maven
        run: |
          cp obp-api/src/main/resources/props/test.default.props.template obp-api/src/main/resources/props/test.default.props
          MAVEN_OPTS="-Xmx2048m -Xms1024m -Xss2048k -XX:MaxPermSize=1024m" mvn package